// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testutil

import (
	"context"

	"github.com/phishbin/src/httpc"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// Bit provides a mock function for the type MockProvider
func (_mock *MockProvider) Bit() uint32 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Bit")
	}

	var r0 uint32
	if returnFunc, ok := ret.Get(0).(func() uint32); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint32)
	}
	return r0
}

// MockProvider_Bit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bit'
type MockProvider_Bit_Call struct {
	*mock.Call
}

// Bit is a helper method to define mock.On call
func (_e *MockProvider_Expecter) Bit() *MockProvider_Bit_Call {
	return &MockProvider_Bit_Call{Call: _e.mock.On("Bit")}
}

func (_c *MockProvider_Bit_Call) Run(run func()) *MockProvider_Bit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_Bit_Call) Return(v uint32) *MockProvider_Bit_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockProvider_Bit_Call) RunAndReturn(run func() uint32) *MockProvider_Bit_Call {
	_c.Call.Return(run)
	return _c
}

// Fetch provides a mock function for the type MockProvider
func (_mock *MockProvider) Fetch(ctx context.Context, c *httpc.Client, emit func(urlData string)) error {
	ret := _mock.Called(ctx, c, emit)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *httpc.Client, func(urlData string)) error); ok {
		r0 = returnFunc(ctx, c, emit)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProvider_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockProvider_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - c *httpc.Client
//   - emit func(urlData string)
func (_e *MockProvider_Expecter) Fetch(ctx any, c any, emit any) *MockProvider_Fetch_Call {
	return &MockProvider_Fetch_Call{Call: _e.mock.On("Fetch", ctx, c, emit)}
}

func (_c *MockProvider_Fetch_Call) Run(run func(ctx context.Context, c *httpc.Client, emit func(urlData string))) *MockProvider_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *httpc.Client
		if args[1] != nil {
			arg1 = args[1].(*httpc.Client)
		}
		var arg2 func(urlData string)
		if args[2] != nil {
			arg2 = args[2].(func(urlData string))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProvider_Fetch_Call) Return(err error) *MockProvider_Fetch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProvider_Fetch_Call) RunAndReturn(run func(ctx context.Context, c *httpc.Client, emit func(urlData string)) error) *MockProvider_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockProvider
func (_mock *MockProvider) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProvider_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockProvider_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockProvider_Expecter) Name() *MockProvider_Name_Call {
	return &MockProvider_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockProvider_Name_Call) Run(run func()) *MockProvider_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_Name_Call) Return(s string) *MockProvider_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProvider_Name_Call) RunAndReturn(run func() string) *MockProvider_Name_Call {
	_c.Call.Return(run)
	return _c
}
